Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 132, in reproduction
    offspring_1 = self.mutation(offspring_1)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 133, in reproduction
    offspring_2 = self.mutation(offspring_2)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 133, in reproduction
    offspring_2 = self.mutation(offspring_2)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
[1, 3, 5]
solution: [1, 3, 5], evaluation: 0.193548
[1, 5, 8]
solution: [1, 5, 8], evaluation: 0.192895
[1, 2, 3, 5]
solution: [1, 2, 3, 5], evaluation: 0.179523
[1, 2, 5, 8]
solution: [1, 2, 5, 8], evaluation: 0.172601
[0, 1, 3, 5]
solution: [0, 1, 3, 5], evaluation: 0.160793
[0, 1, 2, 3, 5]
solution: [0, 1, 2, 3, 5], evaluation: 0.156664
[0, 1, 2, 5, 8]
solution: [0, 1, 2, 5, 8], evaluation: 0.137133
[0, 1, 2, 5]
solution: [0, 1, 2, 5], evaluation: 0.136104
[1, 2, 5, 6]
solution: [1, 2, 5, 6], evaluation: 0.123010
[1, 5, 7]
solution: [1, 5, 7], evaluation: 0.111924

Best solution found (0.19354791533869617, [(1, 0.3416321601976316), (3, 0.06778501342672949), (5, 0.6442518003361569)])

Total elapsed time: 00h20m26.0s
[1, 3, 5]
solution: [1, 3, 5], evaluation: 0.193854
[1, 5, 8]
solution: [1, 5, 8], evaluation: 0.191671
[0, 1, 5, 7]
solution: [0, 1, 5, 7], evaluation: 0.134234
[0, 1, 5, 8]
solution: [0, 1, 5, 8], evaluation: 0.130928
[1, 5, 7]
solution: [1, 5, 7], evaluation: 0.112082
[1, 5, 6, 7]
solution: [1, 5, 6, 7], evaluation: 0.104378
[1, 2, 5]
solution: [1, 2, 5], evaluation: 0.097390
[0, 1, 5, 6, 7]
solution: [0, 1, 5, 6, 7], evaluation: 0.094952
[1, 5, 6]
solution: [1, 5, 6], evaluation: 0.088529
[0, 1, 5, 6]
solution: [0, 1, 5, 6], evaluation: 0.059964

Best solution found (0.19385407070063293, [(1, 0.3416321601976316), (3, 0.06778501342672949), (5, 0.6442518003361569)])

Total elapsed time: 00h16m32.0s
[1, 3, 5]
solution: [1, 3, 5], evaluation: 0.194143
[1, 5, 8]
solution: [1, 5, 8], evaluation: 0.192159
[1, 2, 3, 5]
solution: [1, 2, 3, 5], evaluation: 0.178913
[0, 1, 3, 5]
solution: [0, 1, 3, 5], evaluation: 0.159255
[0, 1, 2, 3, 5]
solution: [0, 1, 2, 3, 5], evaluation: 0.156687
[1, 5, 7]
solution: [1, 5, 7], evaluation: 0.112598
[1, 5, 6, 7]
solution: [1, 5, 6, 7], evaluation: 0.103589
[1, 2, 5]
solution: [1, 2, 5], evaluation: 0.097801
[0, 1, 5, 6, 7]
solution: [0, 1, 5, 6, 7], evaluation: 0.089984
[1, 5, 6]
solution: [1, 5, 6], evaluation: 0.089225

Best solution found (0.19414310452532121, [(1, 0.3416321601976316), (3, 0.06778501342672949), (5, 0.6442518003361569)])

Total elapsed time: 00h17m52.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 133, in reproduction
    offspring_2 = self.mutation(offspring_2)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 132, in reproduction
    offspring_1 = self.mutation(offspring_1)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 132, in reproduction
    offspring_1 = self.mutation(offspring_1)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 354, in main
    max_gen_reached = ga.run()
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 174, in run
    self.generate_population(self.select_parents())[:self.population_size-self.elite_size]
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 145, in generate_population
    p_1, p_2 = self.reproduction(selected_parents[i1].id, selected_parents[i2].id)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 133, in reproduction
    offspring_2 = self.mutation(offspring_2)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 113, in mutation
    offspring = self.strong_mutation(offspring)
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 100, in strong_mutation
    p1p2 = self.select_p1_p2() # get p1p2
  File "/home/marcos/github/brunotcc/bruno/modules/ga.py", line 92, in select_p1_p2
    p1 = random.randint(1, self.n_items/2)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 193, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
[154, 20, 73]
solution: [154, 20, 73], evaluation: 0.026532
[154, 18, 73]
solution: [154, 18, 73], evaluation: 0.025117
[14, 154, 73]
solution: [14, 154, 73], evaluation: 0.024376
[154, 27, 73]
solution: [154, 27, 73], evaluation: 0.023693
[154, 37, 73]
solution: [154, 37, 73], evaluation: 0.023254
[154, 40, 73]
solution: [154, 40, 73], evaluation: 0.022613
[101, 154, 73]
solution: [101, 154, 73], evaluation: 0.022288
[112, 154, 73]
solution: [112, 154, 73], evaluation: 0.022185
[0, 154, 73]
solution: [0, 154, 73], evaluation: 0.020982
[154, 38, 73]
solution: [154, 38, 73], evaluation: 0.020133

Best solution found (0.026532181593983357, [(154, 0.04112472226123591), (20, 0.04313498873786846), (73, 0.033865820229279336)])

Total elapsed time: 00h07m48.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution1.csv'
[114, 19, 32, 68, 71]
solution: [114, 19, 32, 68, 71], evaluation: -0.012127
[114, 19, 32, 71]
solution: [114, 19, 32, 71], evaluation: -0.015738
[112, 19, 32, 71]
solution: [112, 19, 32, 71], evaluation: -0.016806
[114, 16, 19, 32, 71]
solution: [114, 16, 19, 32, 71], evaluation: -0.018366
[112, 19, 32, 68, 71]
solution: [112, 19, 32, 68, 71], evaluation: -0.021516
[110, 114, 19, 32, 68, 71]
solution: [110, 114, 19, 32, 68, 71], evaluation: -0.021623
[112, 16, 19, 32, 71]
solution: [112, 16, 19, 32, 71], evaluation: -0.022932
[114, 16, 19, 32, 68, 71]
solution: [114, 16, 19, 32, 68, 71], evaluation: -0.026695
[110, 114, 16, 19, 32, 71]
solution: [110, 114, 16, 19, 32, 71], evaluation: -0.027589
[117, 121, 19, 32, 68, 71]
solution: [117, 121, 19, 32, 68, 71], evaluation: -0.027720

Best solution found (-0.012127357696929193, [(114, 0.03371765923524395), (19, 0.04106513129062397), (32, 0.035145989894234946), (68, 0.04040788306994527), (71, 0.040600223469474776)])

Total elapsed time: 00h08m28.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution2.csv'
[104, 12, 132]
solution: [104, 12, 132], evaluation: 0.030927
[12, 132, 97]
solution: [12, 132, 97], evaluation: 0.030181
[12, 132, 169]
solution: [12, 132, 169], evaluation: 0.029274
[12, 132, 91]
solution: [12, 132, 91], evaluation: 0.028269
[101, 12, 132]
solution: [101, 12, 132], evaluation: 0.026500
[12, 132, 31]
solution: [12, 132, 31], evaluation: 0.025716
[12, 132, 46]
solution: [12, 132, 46], evaluation: 0.025451
[102, 12, 132]
solution: [102, 12, 132], evaluation: 0.024850
[12, 132, 172, 9]
solution: [12, 132, 172, 9], evaluation: 0.024586
[12, 132, 168]
solution: [12, 132, 168], evaluation: 0.024581

Best solution found (0.030926747390132507, [(104, 0.043036005219792416), (12, 0.040276351630008436), (132, 0.04024701989819883)])

Total elapsed time: 00h09m55.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution3.csv'
[130, 76, 8]
solution: [130, 76, 8], evaluation: 0.027378
[130, 8, 86]
solution: [130, 8, 86], evaluation: 0.025559
[130, 31, 8]
solution: [130, 31, 8], evaluation: 0.024680
[130, 177, 8]
solution: [130, 177, 8], evaluation: 0.024235
[133, 31, 8]
solution: [133, 31, 8], evaluation: 0.022307
[130, 66, 8]
solution: [130, 66, 8], evaluation: 0.019701
[130, 8, 94]
solution: [130, 8, 94], evaluation: 0.019422
[130, 33, 8]
solution: [130, 33, 8], evaluation: 0.019074
[130, 37, 8]
solution: [130, 37, 8], evaluation: 0.018974
[130, 48, 8]
solution: [130, 48, 8], evaluation: 0.017697

Best solution found (0.02737761935767348, [(130, 0.03411208999102496), (76, 0.04078863842492687), (8, 0.03690857308827478)])

Total elapsed time: 00h07m23.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution4.csv'
[0, 146, 70]
solution: [0, 146, 70], evaluation: 0.027942
[0, 146, 41]
solution: [0, 146, 41], evaluation: 0.027175
[0, 146, 89]
solution: [0, 146, 89], evaluation: 0.027056
[0, 146, 42]
solution: [0, 146, 42], evaluation: 0.025197
[0, 146, 47]
solution: [0, 146, 47], evaluation: 0.024795
[0, 146, 64]
solution: [0, 146, 64], evaluation: 0.023535
[0, 146, 57]
solution: [0, 146, 57], evaluation: 0.021216
[0, 146, 28]
solution: [0, 146, 28], evaluation: 0.021167
[0, 146, 82]
solution: [0, 146, 82], evaluation: 0.020232
[0, 146, 46]
solution: [0, 146, 46], evaluation: 0.019310

Best solution found (0.02794200823633641, [(0, 0.06940198192383933), (146, 0.03220696487095808), (70, 0.03545651479231358)])

Total elapsed time: 00h08m34.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution5.csv'
[156, 23, 93]
solution: [156, 23, 93], evaluation: 0.023123
[156, 29, 93]
solution: [156, 29, 93], evaluation: 0.022650
[156, 19, 93]
solution: [156, 19, 93], evaluation: 0.021872
[150, 23, 93]
solution: [150, 23, 93], evaluation: 0.021085
[150, 19, 93]
solution: [150, 19, 93], evaluation: 0.017246
[169, 23, 93]
solution: [169, 23, 93], evaluation: 0.016972
[156, 26, 93]
solution: [156, 26, 93], evaluation: 0.016093
[150, 50, 93]
solution: [150, 50, 93], evaluation: 0.015212
[165, 23, 93]
solution: [165, 23, 93], evaluation: 0.011375
[169, 29, 93]
solution: [169, 29, 93], evaluation: 0.009969

Best solution found (0.023122754967379443, [(156, 0.044155732476467875), (23, 0.033812277001290504), (93, 0.03985459089544566)])

Total elapsed time: 00h06m34.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution6.csv'
[139, 41, 85]
solution: [139, 41, 85], evaluation: 0.031760
[139, 41, 91]
solution: [139, 41, 91], evaluation: 0.027360
[139, 39, 91]
solution: [139, 39, 91], evaluation: 0.027305
[139, 41, 89]
solution: [139, 41, 89], evaluation: 0.026219
[1, 139, 39]
solution: [1, 139, 39], evaluation: 0.024729
[139, 40, 85]
solution: [139, 40, 85], evaluation: 0.024103
[139, 19, 85]
solution: [139, 19, 85], evaluation: 0.023886
[10, 116, 165]
solution: [10, 116, 165], evaluation: 0.022925
[139, 49, 85]
solution: [139, 49, 85], evaluation: 0.022251
[116, 165, 85]
solution: [116, 165, 85], evaluation: 0.021956

Best solution found (0.03176027151619731, [(139, 0.03320718118924879), (41, 0.041836963008404025), (85, 0.03492820723437784)])

Total elapsed time: 00h11m01.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution7.csv'
[115, 166, 5]
solution: [115, 166, 5], evaluation: 0.027520
[114, 166, 5]
solution: [114, 166, 5], evaluation: 0.027212
[125, 166, 47]
solution: [125, 166, 47], evaluation: 0.024448
[166, 47, 8]
solution: [166, 47, 8], evaluation: 0.022330
[113, 166, 5]
solution: [113, 166, 5], evaluation: 0.021755
[119, 166, 47]
solution: [119, 166, 47], evaluation: 0.021628
[125, 166, 5]
solution: [125, 166, 5], evaluation: 0.018681
[116, 166, 5]
solution: [116, 166, 5], evaluation: 0.018393
[133, 166, 99]
solution: [133, 166, 99], evaluation: 0.017467
[166, 5, 64]
solution: [166, 5, 64], evaluation: 0.017315

Best solution found (0.027519741607632146, [(115, 0.04056291451517449), (166, 0.042748829338673966), (5, 0.03389029648143844)])

Total elapsed time: 00h10m13.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution8.csv'
[155, 32, 68]
solution: [155, 32, 68], evaluation: 0.030269
[142, 32, 68]
solution: [142, 32, 68], evaluation: 0.028033
[155, 32, 75]
solution: [155, 32, 75], evaluation: 0.024602
[156, 47, 95]
solution: [156, 47, 95], evaluation: 0.022098
[0, 32, 68]
solution: [0, 32, 68], evaluation: 0.021172
[113, 155, 32]
solution: [113, 155, 32], evaluation: 0.020624
[152, 32, 68]
solution: [152, 32, 68], evaluation: 0.020511
[155, 32, 67]
solution: [155, 32, 67], evaluation: 0.020125
[155, 41, 92]
solution: [155, 41, 92], evaluation: 0.019984
[155, 32, 66]
solution: [155, 32, 66], evaluation: 0.019848

Best solution found (0.03026870708684729, [(155, 0.03431924719214948), (32, 0.035145989894234946), (68, 0.04040788306994527)])

Total elapsed time: 00h07m34.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution9.csv'
[119, 26, 67]
solution: [119, 26, 67], evaluation: 0.028202
[119, 170, 26]
solution: [119, 170, 26], evaluation: 0.025207
[119, 26, 69]
solution: [119, 26, 69], evaluation: 0.025170
[119, 26, 71]
solution: [119, 26, 71], evaluation: 0.024126
[119, 26, 70]
solution: [119, 26, 70], evaluation: 0.023588
[119, 154, 26]
solution: [119, 154, 26], evaluation: 0.023495
[119, 145, 26]
solution: [119, 145, 26], evaluation: 0.023425
[119, 159, 43]
solution: [119, 159, 43], evaluation: 0.023180
[119, 15, 159]
solution: [119, 15, 159], evaluation: 0.023121
[119, 43, 79]
solution: [119, 43, 79], evaluation: 0.022317

Best solution found (0.0282022315700117, [(119, 0.04244101201207155), (26, 0.03354523988855587), (67, 0.04237245546134)])

Total elapsed time: 00h11m00.0s
Traceback (most recent call last):
  File "./ga_setpack.py", line 379, in <module>
    main()
  File "./ga_setpack.py", line 376, in main
    save_solutions(ga, data, elapsed_time, max_gen_reached, args)
  File "./ga_setpack.py", line 290, in save_solutions
    fp = open(args.csv_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'solutions/ga/convulsao/solution10.csv'

Elite:
[1, 3, 5]
solution: [1, 3, 5], evaluation: 0.193673
[1, 5, 8]
solution: [1, 5, 8], evaluation: 0.191034
[1, 2, 3, 5]
solution: [1, 2, 3, 5], evaluation: 0.180171
[1, 2, 5, 8]
solution: [1, 2, 5, 8], evaluation: 0.167519
[0, 1, 3, 5]
solution: [0, 1, 3, 5], evaluation: 0.159309
[0, 1, 2, 3, 5]
solution: [0, 1, 2, 3, 5], evaluation: 0.156776
[0, 1, 2, 5, 8]
solution: [0, 1, 2, 5, 8], evaluation: 0.142341
[0, 1, 2, 5]
solution: [0, 1, 2, 5], evaluation: 0.137383
[0, 1, 5, 8]
solution: [0, 1, 5, 8], evaluation: 0.130046
[1, 2, 5, 6]
solution: [1, 2, 5, 6], evaluation: 0.124038

Best solution found (0.19367312699559824, [(1, 0.3416321601976316), (3, 0.06778501342672949), (5, 0.6442518003361569)])

Total elapsed time: 00h41m39.0s

Elite:
[1, 3, 5]
solution: [1, 3, 5], evaluation: 0.193657
[1, 5, 8]
solution: [1, 5, 8], evaluation: 0.191912
[1, 2, 3, 5]
solution: [1, 2, 3, 5], evaluation: 0.179845
[1, 2, 5, 8]
solution: [1, 2, 5, 8], evaluation: 0.172660
[0, 1, 3, 5]
solution: [0, 1, 3, 5], evaluation: 0.161185
[0, 1, 2, 3, 5]
solution: [0, 1, 2, 3, 5], evaluation: 0.155929
[0, 1, 5, 7]
solution: [0, 1, 5, 7], evaluation: 0.137795
[0, 1, 2, 5, 8]
solution: [0, 1, 2, 5, 8], evaluation: 0.135305
[0, 1, 2, 5]
solution: [0, 1, 2, 5], evaluation: 0.135183
[0, 1, 5, 8]
solution: [0, 1, 5, 8], evaluation: 0.120037

Best solution found (0.19365708892095987, [(1, 0.3416321601976316), (3, 0.06778501342672949), (5, 0.6442518003361569)])

Total elapsed time: 00h47m09.0s

Elite:
[1, 5, 8]
solution: [1, 5, 8], evaluation: 0.192941
[1, 3, 5]
solution: [1, 3, 5], evaluation: 0.192574
[1, 2, 5, 8]
solution: [1, 2, 5, 8], evaluation: 0.168300
[0, 1, 2, 5, 8]
solution: [0, 1, 2, 5, 8], evaluation: 0.141576
[0, 1, 5, 8]
solution: [0, 1, 5, 8], evaluation: 0.140162
[1, 5, 7]
solution: [1, 5, 7], evaluation: 0.111609
[1, 5, 6, 7]
solution: [1, 5, 6, 7], evaluation: 0.104378
[0, 1, 5, 6, 7]
solution: [0, 1, 5, 6, 7], evaluation: 0.098529
[1, 2, 5]
solution: [1, 2, 5], evaluation: 0.095144
[1, 5, 6]
solution: [1, 5, 6], evaluation: 0.089047

Best solution found (0.19294090283743837, [(1, 0.3416321601976316), (5, 0.6442518003361569), (8, 0.05291543064819086)])

Total elapsed time: 00h41m20.0s
